Repository nanoframework/nanoFramework.TestFramework, pull requests merged in 2021-05, with the labels that each got.

#46 Update Test adapter
  source/TestAdapter/Executor.cs
  source/TestAdapter/nanoFramework.TestAdapter.csproj
  source/TestFramework/nanoFramework.TestFramework.nfproj
  source/TestFramework/packages.config
  source/UnitTestLauncher/nanoFramework.UnitTestLauncher.nfproj
  source/UnitTestLauncher/packages.config
Labels: Type: dependencies

#47 Replace Debug with Console.WriteLine for messages
  source/UnitTestLauncher/Program.cs
Labels: Type: enhancement

#56 Fixed copy/paste error in the message for Assert.NotEqual
  source/TestFramework/TestFramework.cs
Labels: Type: Unit Tests, Type: bug

#63 Clean up messages and make all messages consistent
  source/TestFramework/TestFramework.cs
Labels: Type: enhancement
