Repository nanoframework/nanoFramework.TestFramework, pull requests merged in 2021-03, with the labels that each got.

#10 Adjusting TestAdapter logging, adding personal message to Assert
  azure-pipelines.yml
  poc/TestOfTestFramework/NFUnitTest.nfproj
  poc/TestOfTestFramework/Test.cs
  poc/TestOfTestFramework/packages.config
  source/TestAdapter/Executor.cs
  source/TestFramework/TestFramework.cs
  source/package.nuspec
Labels: Area: Config-and-Build, Type: bug, Type: dependencies, Type: enhancement

#11 Fix nuspec
  README.md
  source/package.nuspec
Labels: Area: Config-and-Build

#12 Update nanoCLR to 1.6.1-preview.208
  source/TestAdapter/nanoFramework.TestAdapter.csproj
Labels: Type: dependencies

#13 Miscellaneous improvements
  source/TestAdapter/Executor.cs
Labels: Type: enhancement

#14 Update mscorlib to 1.10.1-preview.11
  source/TestFramework/nanoFramework.TestFramework.nfproj
  source/TestFramework/packages.config
  source/UnitTestLauncher/nanoFramework.UnitTestLauncher.nfproj
  source/UnitTestLauncher/packages.config
Labels: Type: dependencies

#17 Update 2 nuget dependencies
  poc/TestOfTestFramework/NFUnitTest.nfproj
  source/TestAdapter/nanoFramework.TestAdapter.csproj
  source/TestFramework/nanoFramework.TestFramework.nfproj
  source/UnitTestLauncher/nanoFramework.UnitTestLauncher.nfproj
Labels: Type: dependencies

#18 Adjust nanoClr finding path
  source/TestAdapter/Executor.cs
  source/TestAdapter/TestObjectHelper.cs
Labels: Type: bug, Type: enhancement

#20 Remove logger when not initialized
  source/TestAdapter/Executor.cs
Labels: Type: bug

#21 Add debugger helper
  source/TestAdapter/Discover.cs
  source/TestAdapter/Executor.cs
  source/TestAdapter/FodyWeavers.xml
  source/TestAdapter/FodyWeavers.xsd
  source/TestAdapter/Utilities/DebuggerHelper.cs
  source/TestAdapter/nanoFramework.TestAdapter.csproj
Labels: Type: enhancement

#22 Adding global try
  source/TestAdapter/Executor.cs
Labels: Type: bug, Type: enhancement

#23 Rework approach for debugging test adapter
  nanoFramework.TestAdapter.ChildProcessDbgSettings
  nanoFramework.TestAdapter.sln
  source/TestAdapter/Discover.cs
  source/TestAdapter/Executor.cs
  source/TestAdapter/Properties/launchSettings.json
  source/TestAdapter/README.md
  source/TestAdapter/Utilities/DebuggerHelper.cs
  source/TestAdapter/nanoFramework.TestAdapter.csproj
Labels: Area: Config-and-Build, Type: enhancement

#25 Remove timeout from settings
  source/TestAdapter/Executor.cs
  source/TestAdapter/Settings.cs
Labels: Breaking-change, Type: enhancement

#27 Adding general try
  source/TestAdapter/Executor.cs
Labels: Type: bug, Type: enhancement

#32 Add target to download nanoCLR on build
  poc/TestOfTestFramework/NFUnitTest.nfproj
  poc/TestOfTestFramework/packages.config
  source/nanoFramework.TestFramework.targets
  source/package.nuspec
Labels: Type: enhancement

#33 Adding skipped test, correcting Assert.Throws
  poc/NFUnit Test DemoByReference.sln
  poc/TestOfTestFrameworkByReference/NFUnitTestByReference.nfproj
  poc/TestOfTestFrameworkByReference/Properties/AssemblyInfo.cs
  poc/TestOfTestFrameworkByReference/SkipFewMethods.cs
  poc/TestOfTestFrameworkByReference/SkipTestClass.cs
  poc/TestOfTestFrameworkByReference/Test.cs
  poc/TestOfTestFrameworkByReference/nano.runsettings
  poc/TestOfTestFrameworkByReference/packages.config
  source/TestAdapter/Executor.cs
  source/TestAdapter/Properties/launchSettings.json
  source/TestFramework/TestFramework.cs
  source/TestFrameworkShared/SkipTestException.cs
  source/TestFrameworkShared/TestFrameworkShared.projitems
  source/UnitTestLauncher/Program.cs
Labels: Breaking-change, Type: bug, Type: enhancement

#37 Move repository to Cloudsmith
  poc/TestOfTestFramework/NFUnitTest.nfproj
  poc/TestOfTestFramework/packages.config
  poc/TestOfTestFrameworkByReference/NFUnitTestByReference.nfproj
  poc/TestOfTestFrameworkByReference/packages.config
  source/TestAdapter/nanoFramework.TestAdapter.csproj
  source/TestFramework/nanoFramework.TestFramework.nfproj
  source/UnitTestLauncher/nanoFramework.UnitTestLauncher.nfproj
  source/nanoFramework.TestFramework.targets
Labels: Type: dependencies, Type: enhancement
