Repository nanoframework/nanoFramework.TestFramework, pull requests merged in 2024-05, with the labels that each got.

#252 Add CallerArgumentExpression to IsTrue/IsFalse
  source/TestFramework/Assert.cs
  source/TestFramework/nanoFramework.TestFramework.nfproj
Labels: Type: enhancement

#254 Add CallerArgumentExpression to IsNull/IsNotNull
  source/TestFramework/Assert.cs
Labels: Type: enhancement

#257 Update Microsoft.TestPlatform.ObjectModel for dependabot
  source/TestAdapter/nanoFramework.TestAdapter.csproj
  source/TestAdapter/packages.lock.json
Labels: Type: dependencies

#258 Remove Private from System.Runtime reference
  source/TestFramework/nanoFramework.TestFramework.nfproj
Labels: Area: Config-and-Build
