Repository nanoframework/nanoFramework.TestFramework, pull requests merged in 2024-11, with the labels that each got.

#271 Adding `GlobalExclusiveDeviceAccess`
  .editorconfig
  source/TestAdapter/Executor.cs
  spelling_exclusion.dic
Labels: Type: enhancement

#279 Add missing ref to share project
  source/UnitTestLauncher/nanoFramework.UnitTestLauncher.nfproj
  version.json
Labels: Area: Config-and-Build

#280 Remove wrong reference to share project
  source/UnitTestLauncher/nanoFramework.UnitTestLauncher.nfproj
Labels: Area: Config-and-Build

#282 Update nanoFramework.Tools.Debugger.NET
  source/TestAdapter/nanoFramework.TestAdapter.csproj
  source/TestAdapter/packages.lock.json
Labels: Type: dependencies

#283 Update CliWrap to 3.6.7
  source/TestAdapter/nanoFramework.TestAdapter.csproj
  source/TestAdapter/packages.lock.json
Labels: Type: dependencies

#284 Rework test adapter project
  poc/TestOfTestFrameworkByReference/nano.runsettings
  source/TestAdapter/nanoFramework.TestAdapter.csproj
  source/TestAdapter/packages.lock.json
  source/package.nuspec
Labels: Area: Config-and-Build, Type: dependencies

#286 Update nanoFramework.Tools.Debugger.Net v2.5.6
  source/TestAdapter/nanoFramework.TestAdapter.csproj
  source/TestAdapter/packages.lock.json
Labels: Type: dependencies
