Repository nanoframework/nanoFramework.TestFramework, pull requests merged in 2025-02, with the labels that each got.

#300 Migrate to HTTP client
  source/TestAdapter/NanoCLRHelper.cs
  source/TestAdapter/nanoFramework.TestAdapter.csproj
  source/TestAdapter/packages.lock.json
Labels: Type: enhancement

#301 Miscellaneous fixes in IntelliSense comments
  source/TestFramework/Assert.cs
  source/TestFramework/CollectionAssert.cs
Labels: Type: documentation

#302 Remove types that are now available from mscorlib
  source/TestFramework/CallerArgumentExpressionAttribute.cs
  source/TestFramework/NullableAttributes.cs
  source/TestFramework/nanoFramework.TestFramework.nfproj
Labels: Type: enhancement, Breaking-change

#304 Replace "Content-Type" with "Accept" when checking nanoclr version
  source/TestAdapter/NanoCLRHelper.cs
Labels: Type: bug
